name: Repo Moderator

on:
  issues: 
    types: [labeled, unlabeled, closed, reopened, assigned] 
  pull_request:
    types: [closed, reopened, assigned]

jobs:
  revert-action:
    if: github.actor != 'C4-Staff'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Revert Label Changes
        uses: geoffchan23/repo-moderator@main
        with:
          github-token: ${{ secrets.LABEL_REMOVER_GITHUB_TOKEN }}
          sponsor-team-slug: "2022-01-dev-test-repo-sponsors"
          allowed-labels: "sponsor confirmed, sponsor disputed, sponsor acknowledged, disagree with severity"