name: Revert Label Changes

on:
  issues: 
    types: [labeled, unlabeled, closed, reopened, assigned] 
  pull_request:
    types: [closed, reopened, assigned]
  issue_comment: # For handling hidden comments
    types: 
      - created 
      - edited
      - deleted 
  discussion_deleted: 
  discussion_category_changed: 

jobs:
  revert-label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Revert Label Changes
        uses: geoffchan23/label-reverter@main # Replace with your action's repository
        with:
          github-token: ${{ secrets.LABEL_REMOVER_GITHUB_TOKEN }}
          sponsor-team-slug: "2022-01-dev-test-repo-sponsors"
          allowed-labels: "sponsor confirmed, sponsor disputed, sponsor acknowledged, disagree with severity"
