name: Repo Moderator

on:
  issues: 
    types: [labeled, unlabeled, closed, reopened, assigned, unassigned] 
  pull_request:
    types: [closed, reopened, assigned, unassigned]

jobs:
  revert-action:
    if: github.actor != 'C4-Staff'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Repo Moderator
        uses: code-423n4/repo-moderator
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sponsor-team-slug: "2022-01-dev-test-repo-sponsors"
          allowed-labels: "sponsor confirmed, sponsor disputed, sponsor acknowledged"